Feature email
vitalysologubov/AVHelpdesk pull request #1
Opened 2020-09-25 15:22 UTC by da070116

2020-09-25 17:07 UTC, vitalysologubov commented on av_mail.py
> +    subject = subject.decode(encoding)
Получаю AttributeError: 'str' object has no attribute 'decode' при обработке письма.

2020-09-25 20:28 UTC, sobrabd requested changes

2020-09-25 20:28 UTC, sobrabd commented on av_mail.py
> +class MLStripper(HTMLParser):
Есть готовое решение
https://www.crummy.com/software/BeautifulSoup/bs4/doc.ru/bs4ru.html#id7

soup.get_text()
парсит немного лучше чем твой вариант

2020-09-25 20:28 UTC, sobrabd commented on av_mail.py
> +        result = message.get_payload(decode=True).decode('utf-8')
можно по идеи сразу тут написать return message ...
а последний if убрать, функция по умаолчанию все равно возвращает None

2020-09-25 20:28 UTC, sobrabd commented on av_mail.py
> +        result = message.get_payload(decode=True).decode('utf-8')
Конечно тесты мастхев, код уже немаленький, обязательно в след итерации нужно написать

2020-09-25 20:28 UTC, sobrabd commented on av_mail.py
> +def fetch_mail():
длинная функция, сложновато читать и тестить тоже будет сложновато, нужно разбить на мелкие функции

2020-09-25 20:28 UTC, sobrabd commented on av_mail.py
> +    mail.login('av-helpdesk@yandex.ru', EMAIL_PASSWORD)
61-63 можно вынести в функцию login_email

2020-09-25 20:28 UTC, sobrabd commented on av_mail.py
> +    mail.list()
наверное можно убрать

2020-09-25 20:28 UTC, sobrabd commented on av_mail.py
> +        raw_email = data[0][1]
65-73 можно написать генератор, который будет выдавать по одному, генераторы занимают меьше памяти и гораздо быстрее чем листы, потом нужно будет отработать stop iteration error
https://realpython.com/introduction-to-python-generators/

2020-09-25 20:28 UTC, sobrabd commented on av_mail.py
> +        message_content['body'] = strip_tags(body)
85-90 функция создания body письма

2020-09-25 20:28 UTC, sobrabd commented on av_mail.py
> +        msg_list.append(message_content)
отдельно можно добавить функцию составления messagecontent

2020-09-25 20:28 UTC, sobrabd commented on av_mail.py
> +    subject = subject.decode(encoding)
Сейчас пока нужно пофиксить и помаксимуму потестить руками, чтобы отловить еще какие-то баги

2020-09-25 20:28 UTC, sobrabd commented on server.py
> +            for header in message['headers']:
потом будем рендерить в шаблон, я поставлю таску в трело

2020-09-25 20:30 UTC, sobrabd commented
Общее замечание, тут получается очень много коммитов, их нужно будет сосквошить
https://htmlacademy.ru/blog/boost/tools/how-to-squash-commits-and-why-it-is-needed
можно это сделать через вебинтерфейс гита, рядом с зеленой кнопкой merge pull request есть выпадающий список

2020-09-25 21:18 UTC, da070116 commented on av_mail.py
> +        result = message.get_payload(decode=True).decode('utf-8')
> 
> 
> можно по идеи сразу тут написать return message ...
> а последний if убрать, функция по умаолчанию все равно возвращает None

это будет нормально читаться?

2020-09-26 09:35 UTC, sobrabd commented on av_mail.py
> +        mcd = get_message_content_dict(
get_message_content_dict можно удалить и просто поставить dict, раьотать будет также по идеи

2020-09-27 12:01 UTC, sobrabd approved these changes
два замечания, и все остальное мне нравится

2020-09-27 12:01 UTC, sobrabd commented on av_mail.py
> +    if not payload_data.isascii():
нельзя ли объеденить три первых if/elif в один статус дать и дать ему какое-то название?

2020-09-27 12:01 UTC, sobrabd commented on av_mail.py
> +def iterate_over_messages(identifiers):
я думал вынести в генератор с 93- 96, так чтобы возвращать отдельные письма, и потом по нему проитерироваться, но в целом можно оставить в таком виде, но тогда этот код 76-81 нужно убрать, так как он ничего не делат

2020-09-29 10:55 UTC, vitalysologubov approved these changes

2020-09-29 16:13 UTC, merged