Feature templates
vitalysologubov/AVHelpdesk pull request #13
Opened 2020-11-09 12:34 UTC by vitalysologubov

2020-11-09 19:32 UTC, sobrabd requested changes
а почему удаляем create admin?

2020-11-09 19:32 UTC, sobrabd commented on webapp/__init__.py
> +    @app.route('/reply_ticket/<ticket_id>/<subject>/<client_id>/<client_email>', methods=['POST'])
очень сложный роут, не читается
роут как правило строится определенным образом
https://habr.com/ru/post/38730/ (почитай тут про построение url)
и посмотри например на урл этой страницы
https://github.com/vitalysologubov/AVHelpdesk/pull/13/files
роут это не способ передать определенные данные а скорее способ соорентировать пользователя о том где он есть в системе.
тут я думаю можно оставить просто reply_ticket/<ticket_id>
а потом сделать запрос и взять оставшиеся данные с тикета

2020-11-09 19:32 UTC, sobrabd commented on webapp/__init__.py
> +        ticket = Ticket.query.filter(Ticket.id == ticket_id).first()
если ты просто берешь по id то можно через get брать
https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.get

2020-11-09 19:32 UTC, sobrabd commented on webapp/__init__.py
> +        ticket.id_status = 4
тут чтобы читалось получше можно провернуть такой фокус
в файле моделей обозначить константы статусов
CLOSED = 4
потом импортировать из моделей в этот файл CLOSED
from models import CLOSED ...
потом тут выставить ticket.id_status = CLOSED
и будет читаться лучше (сейчас типа смотришь такой и думаешь, че за 4

2020-11-09 19:32 UTC, sobrabd commented on webapp/__init__.py
> +            if current_user.is_admin:
я подумал, можно будет потом сделать нормальную админку для админа
https://flask-admin.readthedocs.io/en/v1.0.9/quickstart/

2020-11-09 19:32 UTC, sobrabd commented on webapp/send_email.py
> +    except sqlalchemy.exc.OperationalError as error:
конкретно в этом случае пока не особо нужно, но стоит иметь ввиду, что если происходит много всего то в блоке except часто нужно откатить изменения
https://www.youtube.com/watch?v=P-Z1wXFW4Is

2020-11-12 17:18 UTC, vitalysologubov commented on webapp/__init__.py
> +    @app.route('/reply_ticket/<ticket_id>/<subject>/<client_id>/<client_email>', methods=['POST'])
Согласен. Сделал запросы данных из БД

2020-11-12 17:18 UTC, vitalysologubov commented on webapp/__init__.py
> +        ticket = Ticket.query.filter(Ticket.id == ticket_id).first()
Сделано

2020-11-12 17:19 UTC, vitalysologubov commented on webapp/__init__.py
> +        ticket.id_status = 4
Мне нравится этот фокус)

2020-11-13 10:30 UTC, sobrabd approved these changes

2020-11-13 13:53 UTC, merged