Feature tickets
vitalysologubov/AVHelpdesk pull request #3
Opened 2020-10-01 18:50 UTC by vitalysologubov

2020-10-01 19:26 UTC, sobrabd requested changes

2020-10-01 19:26 UTC, sobrabd commented on webapp/av_mail.py
> +    if encoding:
я бы этот файл оставил без изменений, как я понимаю, у Саши они эти изменени есть,и судя по тому что тут удаяется огромный кусок снизу, ты не от самой последней ветки отпочковался

2020-10-01 19:26 UTC, sobrabd commented on webapp/models.py
> +    id_status = db.Column(db.Integer, db.ForeignKey('ticket_status.id'), nullable=False, default=1)
Если есть изменения в моделях нужно добавить и миграции

2020-10-01 19:26 UTC, sobrabd commented on webapp/add_tickets.py
> +
все круто, но названия переменных могут быть лучше, я предложу ряд названий, которые мне кажутся более читаемыми
Плюс я думаю, что имеет смысл возвращать всего клиента а не тоьлко его id. Такая функция например встроена в django  довольно часто используется.
https://docs.djangoproject.com/en/3.1/ref/models/querysets/#get-or-create
Если мы будем часто этим пользоваться то имеет смысл обобщить для всех моделей

2020-10-01 19:26 UTC, sobrabd commented on webapp/add_tickets.py
> +def check_client(client):
get_or_create_client_by_email(email)

2020-10-01 19:26 UTC, sobrabd commented on webapp/add_tickets.py
> +    checking_client = Client.query.filter(Client.email == client["email"]).first()
client =

2020-10-01 19:26 UTC, sobrabd commented on webapp/add_tickets.py
> +    if checking_client:
if client

2020-10-01 19:26 UTC, sobrabd commented on webapp/add_tickets.py
> +        last_client_id = checking_client.id
return client

2020-10-01 19:26 UTC, sobrabd commented on webapp/add_tickets.py
> +        last_client_id = model.id
return client

2020-10-01 19:26 UTC, sobrabd commented on webapp/add_tickets.py
> +        client['name'] = message['author']
имя нигде не используется судя по всему, его можно убрать
на самом деле словари тут не особо и нужны, поиск происходит по email, поэтому можно явно его и передать
get_or_create_client_by_email(email=message['address']) (можно потом задуматься (в след пр) чтобы переименовать addres в email или from_email

также и со второй частью функции, словарь не нужен, лучше явно указать все переменные при создании тикета
и model это очень обще, это имя лучше использовать, если речь идет реально о какой-то сущности model

тут можно что то типа 
ticket = Ticket(id_client=client.id, subject=message['subject'], content=message['body'])

2020-10-01 19:26 UTC, sobrabd commented on webapp/add_tickets.py
> +        model = Client(**client)
cleint =

2020-10-02 07:28 UTC, vitalysologubov commented on webapp/av_mail.py
> +    if encoding:
Я отпочковался от мастера, просто в нем еще нет этих изменений, поэтому я удалил дублирующую функцию fetch_mail, и поправил decode_mail_header, потому что иначе при обработке писем получал бы ошибку

2020-10-02 18:49 UTC, sobrabd reviewed
Нужно вернуть файлик тестов, а остальное все на мой взгляд выглядит неплохо

2020-10-02 19:23 UTC, da070116 commented on webapp/add_tickets.py
> +def get_or_create_client_by_email(name, email):
name не обязательный параметр тут? если не обязательный, то можно его  через *

2020-10-02 19:24 UTC, da070116 commented on webapp/add_tickets.py
> +def add_ticket(messages):
messages могут быть пустыми?

2020-10-02 19:26 UTC, da070116 approved these changes

2020-10-03 07:50 UTC, vitalysologubov commented on webapp/add_tickets.py
> +def add_ticket(messages):
messages могут быть пустыми, но в таком случае цикл for просто не сработает

2020-10-03 09:20 UTC, sobrabd commented on webapp/add_tickets.py
> +def get_or_create_client_by_email(name, email):
Name сейчас обязательный, в принципе, думаю можно оставить в таком виде.

2020-10-03 09:20 UTC, sobrabd approved these changes

2020-10-03 10:34 UTC, merged