Добавлены тесты клиентов и входящих писем
vitalysologubov/AVHelpdesk pull request #5
Opened 2020-10-08 18:51 UTC by vitalysologubov

2020-10-08 20:23 UTC, sobrabd commented on test_add_tickets.py
> +        model = Ticket(id_client=client.id, subject=message['subject'], content=message['body'])
лучше переименовать model в таск, потому что это таск а не абстрактный model
model - > task

2020-10-08 20:23 UTC, sobrabd commented on test_add_tickets.py
> +def email():
фикстура называется email хотя по факту возвращает таск лучше переименовать

2020-10-09 14:24 UTC, da070116 approved these changes

2020-10-10 13:28 UTC, sobrabd requested changes
Я предлагаю еще немного изменить тесты
1) все написать под pytest
2) в теst add ticket получать message не просто переменной а из функции fetch mail просто если проект разрастется, и кто-то через год другой придет на него он не сразу поймет, а что за messages, а так сразу будет понятно откуда они взялись.

2020-10-10 13:28 UTC, sobrabd commented on webapp/send_email.py
> +def create_body(receiver, subject, message):
Хорошо, что ты разделил эти 2 функции

2020-10-10 13:28 UTC, sobrabd commented on test_add_tickets.py
> +class TestClient(TestCase):
Не очень мне нравится, что тесты написаны под юнит тест, хотя изначально мы начинали на pytest, pytest поддерживает unittest так что они совместимы. работать будет, но на мой взгляд чисто стилистически лучше когда все написано в одном стиле. я так понял ты переписал это чтобы работал mock.patch, он работает только внутри class TestCase поэтому пришлось вставить 1 класс, ну и потом все остальные, думаю, лучше все свести к стилистике pytest
метод send mail можно просто тоже замокать

2020-10-10 13:28 UTC, sobrabd commented on test_add_tickets.py
> +            message = [
Когда говорил про мок писем я имел ввиду, что мы как раз будем делать мок fetch_mail https://github.com/vitalysologubov/AVHelpdesk/blob/master/webapp/av_mail.py#L94

то есть замокать этот метод
...fetch_mail = MagicMock(return_value=<список писем>)
потом вызываем fetch mail, получаем список писем и его обрабатываем, можно как раз проверить что все ок, если есть новые письма, и если их нет

2020-10-11 18:24 UTC, sobrabd requested changes

2020-10-11 18:24 UTC, sobrabd commented on test_add_tickets.py
> +if __name__ == "__main__":
вот это можем убрать
чтобы запускать тесты можем писать pytest path/to/file

2020-10-11 18:24 UTC, sobrabd commented on webapp/add_tickets.py
> +            return False
круто что появился эксепшен
Но  состороны читается странно, что функция add_ticket возвращает true или false, притом эти значения, нужны только для теста. Возможно, если бы эти значения были бы нужны где-то в логике, такие дейтвия были бы оправданы, но вписывать эти значения в функцию только ради тестов на мой взгляд, не стоит.
я бы тут ничего не возвращал, до тех пор пока какие-то значения нам не понадобятся, в блоке эксепшн можно принтом пока(потом можно добавить логи) выводил данные, которые попадают в таск перед сохранением, чтобы понять и отладить в чем была проблема и/или что то делать с этими письмами, например отладываем в специальную папку, чтобымы их не пропустили, и знали что у нас есть проблема.

2020-10-11 18:24 UTC, sobrabd commented on webapp/add_tickets.py
>          model = Ticket(id_client=client.id, subject=message['subject'], content=message['body'])
давай сделаем task =

2020-10-11 18:24 UTC, sobrabd commented on test_add_tickets.py
> +        assert result
Тут я бы проверял, вот что мы берем из бд таски, которые были созданы по этим messages и проверяю их поля (их можно сделать уникальными)

2020-10-12 11:04 UTC, sobrabd approved these changes

2020-10-12 12:15 UTC, merged