Feature email in
vitalysologubov/AVHelpdesk pull request #8
Opened 2020-10-15 11:41 UTC by vitalysologubov

2020-10-15 13:13 UTC, da070116 commented on test_add_tickets.py
> +            task = Ticket.query.filter(Ticket.comments == message['body']).order_by(Ticket.id.desc()).first()
мне кажется, довольно тяжелый запрос для субд - искать совпадения по текстовому полю. Нельзя как-то иначе?

2020-10-15 13:23 UTC, vitalysologubov commented on test_add_tickets.py
> +            task = Ticket.query.filter(Ticket.comments == message['body']).order_by(Ticket.id.desc()).first()
Как вариант можно в add_ticket(messages) возвращать список id всех добавленных в БД заявок, а потом просто делать поиск по этим id.

2020-10-15 13:28 UTC, sobrabd commented on webapp/add_tickets.py
> +def get_date(date):
думаю это можно прописать в моделе через default
https://docs.sqlalchemy.org/en/13/core/defaults.html

2020-10-15 13:28 UTC, sobrabd commented on test_add_tickets.py
> +            task = Ticket.query.filter(Ticket.comments == message['body']).order_by(Ticket.id.desc()).first()
так как это тест который будет прогоняться на пустой бд то норм

2020-10-15 13:28 UTC, sobrabd commented on test_add_tickets.py
> +            task = Ticket.query.filter(Ticket.comments == message['body']).order_by(Ticket.id.desc()).first()
да и в целом не такой уж и тяжелый проверяем один атрибут в й таблице

2020-10-15 13:28 UTC, sobrabd commented on webapp/add_tickets.py
> +        task = Ticket(id_client=client.id, subject=ticked_id + ': ' + message['subject'], comments=message['body'])
не уверен я что в комментах должно лежать именно это
может быть тогда добавим поле description, это будет логично, а comments оставим для заполнения сотрудниками,потом можно будет отдельную сущьность сделать

2020-10-15 13:55 UTC, vitalysologubov commented on webapp/add_tickets.py
> +        task = Ticket(id_client=client.id, subject=ticked_id + ': ' + message['subject'], comments=message['body'])
Согласен, лучше comments оставить только для сотрудников, пусть вся переиска хранится в Message. А description может добавить, когда точно в нем появится необходимость? Или лучше сразу добавить?

2020-10-15 14:56 UTC, sobrabd commented on webapp/add_tickets.py
> +
Функцию можно удалить, если мы используем дефолтное значение

2020-10-15 14:56 UTC, sobrabd commented on webapp/models.py
> +    received_date = db.Column(db.DateTime, nullable=False, default=datetime.now)
Нужно сделать так чтобы она могла быть нулевой, чтобы мы могли сохранять объект без нее, а потом после сохранения дата автоматически проставится

2020-10-15 14:56 UTC, sobrabd commented on test_add_tickets.py
> +            task = Ticket.query.filter(Ticket.comments == message['body']).order_by(Ticket.id.desc()).first()
Ну если нам где то это понадобится, то можно, просто для удобства тестов я бы не добавлял

2020-10-15 14:56 UTC, sobrabd commented on webapp/models.py
> +                f'content={self.comments}')
Тут пока тоже тогда можно убрать

2020-10-15 14:56 UTC, sobrabd commented on webapp/add_tickets.py
> +    try:
Всю функцию можно удалить и пользоваться только дефолтны проставлением даты-времени

2020-10-15 14:56 UTC, sobrabd commented on webapp/models.py
> +    received_date = db.Column(db.DateTime, nullable=False, default=datetime.now)
Чтобы дефолтное значение работало нужно сделать это поле необязательным, тогда мы сможем сохранять без него объект, а при сохранении уже будет проставляться дата время

2020-10-15 14:57 UTC, sobrabd commented on webapp/add_tickets.py
> +        task = Ticket(id_client=client.id, subject=ticked_id + ': ' + message['subject'], comments=message['body'])
Думаю можно и сразу, чтобы записывать туда боди первого письма

2020-10-16 21:30 UTC, sobrabd reviewed
Думаю сразу нужно реализовывать вариант с подписью заголовка

2020-10-16 21:30 UTC, sobrabd commented on webapp/add_tickets.py
> +        if ticket is None:
я бы просто при создании письма создавал какой-то уникальный заголовок, завзанный на  id ticket -a
"Helpdesk ticket 0041: <тема >"
при получении письма, я бы проверял есть ли такой заголовок
Если нет обрабатывал бы как новое письмо,если есть, то обрабатывал бы как новое

2020-10-16 21:30 UTC, sobrabd commented on webapp/add_tickets.py
> +        if ticket is None:
Сложновато получилось

2020-10-16 21:30 UTC, sobrabd commented on webapp/add_tickets.py
> +        ticket_id = str(db.session.query(Ticket).order_by(Ticket.id.desc()).first().id + 1)
Для таких дел можно использовать функции
https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.expression.func
будет как-то так выглядеть
session.query(func.max(Table.column)) 

но мне кажется вся эта функция нам не нужна

2020-10-16 21:38 UTC, sobrabd commented
Прежде чем делать обработку писем с заголовком нужно проставлять этот заголовок при создании таски.

2020-10-17 19:11 UTC, vitalysologubov commented on webapp/add_tickets.py
> +        if ticket is None:
А если сделать в виде "1: <тема>", "315: <тема>" и т.п. для краткости?

2020-10-17 19:19 UTC, vitalysologubov commented on webapp/add_tickets.py
> +        ticket_id = str(db.session.query(Ticket).order_by(Ticket.id.desc()).first().id + 1)
Попробовал использовать func для получения id, вроде работает =) А вот как избавиться от функции получения id заявки, я пока не придумал более оптимального варианта, так как мы в начале ищем все id заявки клиента с определённой темой, если таких id нет, то нам нужно найти id последней заявки (либо если их вообще нет вернуть 1). Можно, конечно, всё из этой функции вынести в add_ticket.

2020-10-18 09:52 UTC, sobrabd commented on webapp/add_tickets.py
> +        return '1'
мы обсудили, что эту функцию мы переделаем, но хотел обратить внимание,что так лучше ничего не возвращать, return <цифра>
лучше сделать так
my_var = <цифра>
return my_var
my_var - понятное название переменной
сейчас тут более менее понятно, что имеется ввиду, но если там будет что-то более сложное то лучше возвращать переменную, которая будет красноречива

2020-10-20 22:29 UTC, sobrabd requested changes

2020-10-20 22:29 UTC, sobrabd commented on webapp/add_tickets.py
> +def get_new_ticket_id():
Эту функцию нужно убрать
Дело в том, что ты делаешь питоном то что должна делать орм и бд, это очень плохо
Sqlalchemy предлагает решение для нашей проблемы:
Использовать id объекта, в теме письма.
https://docs.sqlalchemy.org/en/13/orm/mapped_sql_expr.html#mapper-sql-expressions
думаю первый вариант подойдет

2020-10-21 18:55 UTC, sobrabd commented on webapp/add_tickets.py
> +        ticket_id = ""
а зачем это тут?

2020-10-21 18:55 UTC, sobrabd commented on webapp/add_tickets.py
> +        subject = re.search(r'Helpdesk ticket \d+', message['subject'])
может как-то по другому назовем, эта переменная отвечает на вопрос первичное ли письмо или нет, потому что subject это немного про другое

2020-10-22 15:07 UTC, merged